In [1]:
# Libraries
import pandas as pd
from datetime import datetime

In [2]:
# Constant Variables
# Filenames
EXTRACTED_REAL_TIME_DATA_FILENAME = 'extracted_real_time_data.json'

In [3]:
# Read the data frame from a json file
df = pd.read_json(EXTRACTED_REAL_TIME_DATA_FILENAME, dtype={'RecordedDate': 'str'})
df

,VehicleNo,TripId,RouteNo,Direction,Destination,Pattern,Latitude,Longitude,RecordedTime,RouteMap,RecordedDate
0,16026,13678409,144,NORTH,SFU,NB1,49.225617,-123.004250,06:58:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407
1,16026,13678409,144,NORTH,SFU,NB1,49.225617,-123.003483,06:59:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407
2,16026,13678409,144,NORTH,SFU,NB1,49.225150,-123.002100,07:00:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407
3,16026,13678409,144,NORTH,SFU,NB1,49.224100,-122.999983,07:01:43 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407
4,16026,13678409,144,NORTH,SFU,NB1,49.224367,-122.997567,07:02:24 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407
...,...,...,...,...,...,...,...,...,...,...,...
62767,19045,13717155,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.280067,-122.919800,11:36:20 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409
62768,22012,13717325,R5,WEST,HASTINGS ST / TO BURRARD STN,W1,49.280450,-122.958483,11:36:40 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409
62769,8126,13717184,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.282250,-123.108483,11:35:55 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409
62770,8134,13717218,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.280233,-122.992467,11:36:26 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409
62771,8141,13717219,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.279050,-122.912283,11:22:16 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409

In [4]:
# Convert the date and time strings to datetime
def convert_to_datetime(date, time):
    return datetime.strptime(date + time, '%Y%m%d%I:%M:%S %p')
df['RecordedDateTime'] = df.apply(lambda row: convert_to_datetime(row['RecordedDate'], row['RecordedTime']), axis=1)
df

,VehicleNo,TripId,RouteNo,Direction,Destination,Pattern,Latitude,Longitude,RecordedTime,RouteMap,RecordedDate,RecordedDateTime
0,16026,13678409,144,NORTH,SFU,NB1,49.225617,-123.004250,06:58:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407,2024-04-07 06:58:07
1,16026,13678409,144,NORTH,SFU,NB1,49.225617,-123.003483,06:59:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407,2024-04-07 06:59:07
2,16026,13678409,144,NORTH,SFU,NB1,49.225150,-123.002100,07:00:07 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407,2024-04-07 07:00:07
3,16026,13678409,144,NORTH,SFU,NB1,49.224100,-122.999983,07:01:43 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407,2024-04-07 07:01:43
4,16026,13678409,144,NORTH,SFU,NB1,49.224367,-122.997567,07:02:24 am,{'Href': 'https://nb.translink.ca/geodata/144....,20240407,2024-04-07 07:02:24
...,...,...,...,...,...,...,...,...,...,...,...,...
62767,19045,13717155,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.280067,-122.919800,11:36:20 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409,2024-04-09 23:36:20
62768,22012,13717325,R5,WEST,HASTINGS ST / TO BURRARD STN,W1,49.280450,-122.958483,11:36:40 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409,2024-04-09 23:36:40
62769,8126,13717184,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.282250,-123.108483,11:35:55 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409,2024-04-09 23:35:55
62770,8134,13717218,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.280233,-122.992467,11:36:26 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409,2024-04-09 23:36:26
62771,8141,13717219,R5,EAST,HASTINGS ST / TO SFU EXCHANGE,E1,49.279050,-122.912283,11:22:16 pm,{'Href': 'https://nb.translink.ca/geodata/R5.k...,20240409,2024-04-09 23:22:16

In [5]:
# Drop the unused columns
df.drop(['VehicleNo', 'TripId', 'Destination', 'Pattern', 'RecordedTime', 'RouteMap', 'RecordedDate'], axis=1, inplace=True)
df

      RouteNo Direction   Latitude   Longitude    RecordedDateTime
0         144     NORTH  49.225617 -123.004250 2024-04-07 06:58:07
1         144     NORTH  49.225617 -123.003483 2024-04-07 06:59:07
2         144     NORTH  49.225150 -123.002100 2024-04-07 07:00:07
3         144     NORTH  49.224100 -122.999983 2024-04-07 07:01:43
4         144     NORTH  49.224367 -122.997567 2024-04-07 07:02:24
...       ...       ...        ...         ...                 ...
62767      R5      EAST  49.280067 -122.919800 2024-04-09 23:36:20
62768      R5      WEST  49.280450 -122.958483 2024-04-09 23:36:40
62769      R5      EAST  49.282250 -123.108483 2024-04-09 23:35:55
62770      R5      EAST  49.280233 -122.992467 2024-04-09 23:36:26
62771      R5      EAST  49.279050 -122.912283 2024-04-09 23:22:16

[62772 rows x 5 columns]

In [6]:
# Drop all null values
df.dropna(axis=1, inplace=True)
df

      RouteNo Direction   Latitude   Longitude    RecordedDateTime
0         144     NORTH  49.225617 -123.004250 2024-04-07 06:58:07
1         144     NORTH  49.225617 -123.003483 2024-04-07 06:59:07
2         144     NORTH  49.225150 -123.002100 2024-04-07 07:00:07
3         144     NORTH  49.224100 -122.999983 2024-04-07 07:01:43
4         144     NORTH  49.224367 -122.997567 2024-04-07 07:02:24
...       ...       ...        ...         ...                 ...
62767      R5      EAST  49.280067 -122.919800 2024-04-09 23:36:20
62768      R5      WEST  49.280450 -122.958483 2024-04-09 23:36:40
62769      R5      EAST  49.282250 -123.108483 2024-04-09 23:35:55
62770      R5      EAST  49.280233 -122.992467 2024-04-09 23:36:26
62771      R5      EAST  49.279050 -122.912283 2024-04-09 23:22:16

[62772 rows x 5 columns]

In [7]:
# Drop all duplicates
df.drop_duplicates(inplace=True)
df

      RouteNo Direction   Latitude   Longitude    RecordedDateTime
0         144     NORTH  49.225617 -123.004250 2024-04-07 06:58:07
1         144     NORTH  49.225617 -123.003483 2024-04-07 06:59:07
2         144     NORTH  49.225150 -123.002100 2024-04-07 07:00:07
3         144     NORTH  49.224100 -122.999983 2024-04-07 07:01:43
4         144     NORTH  49.224367 -122.997567 2024-04-07 07:02:24
...       ...       ...        ...         ...                 ...
62766      R5      WEST  49.281233 -123.091633 2024-04-09 23:35:52
62767      R5      EAST  49.280067 -122.919800 2024-04-09 23:36:20
62768      R5      WEST  49.280450 -122.958483 2024-04-09 23:36:40
62769      R5      EAST  49.282250 -123.108483 2024-04-09 23:35:55
62770      R5      EAST  49.280233 -122.992467 2024-04-09 23:36:26

[52571 rows x 5 columns]

In [8]:
# Filter the recorded hour bewteen 7:00 to 23:00
df = df[(df['RecordedDateTime'].dt.hour >= 7) & (df['RecordedDateTime'].dt.hour < 23)]
df

      RouteNo Direction   Latitude   Longitude    RecordedDateTime
2         144     NORTH  49.225150 -123.002100 2024-04-07 07:00:07
3         144     NORTH  49.224100 -122.999983 2024-04-07 07:01:43
4         144     NORTH  49.224367 -122.997567 2024-04-07 07:02:24
5         144     NORTH  49.225700 -122.994100 2024-04-07 07:03:23
6         144     NORTH  49.229850 -122.992800 2024-04-07 07:04:45
...       ...       ...        ...         ...                 ...
62508      R5      EAST  49.285700 -123.114283 2024-04-09 22:59:26
62509      R5      EAST  49.276733 -122.944833 2024-04-09 22:59:37
62510      R5      WEST  49.281050 -123.000083 2024-04-09 22:59:08
62511      R5      WEST  49.285333 -123.115900 2024-04-09 22:59:37
62512      R5      EAST  49.281050 -123.043017 2024-04-09 22:59:22

[51308 rows x 5 columns]